### ISSUE TITLE
Pick a topic

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/524_group4#2]
Come up with a topic for your project. Discuss the topic with your TA or lab instructor and proceed only after your topic has been approved by one of them.

**Comment by mgaroub** [comment]
Choice #1: 
Image Filter 

Choice #2: 
Moving Average

Choice #3: 
Text Preprocessor

**Comment by jiajie0225** [comment]
Final selection: Image Filter

**Comment by mgaroub** [comment]
Topic: Image Filter

**Comment by mgaroub** [comment]
Topic: Image Filters
Repo name: PyGram
